### ISSUE TITLE
希望增加对 AList - Desktop 的支持

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#15]
[alist-org/desktop-release (github.com)](https://github.com/alist-org/desktop-release)

[希望增加 macOS 上 Homebrew 包管理器安装方式的支持 · Issue #15 · alist-org/desktop-release (github.com)](https://github.com/alist-org/desktop-release/issues/15)

**Comment by ivaquero** [comment]
这几天出差了，你先试着搞搞

**Comment by Mrered** [comment]
我在M1上运行的，可以正常跑，没出过bug，我这两天在折腾OpenWRT，不要慌，我还要开一个issue

**Comment by ivaquero** [comment]
我这几天项目有点忙，我加你为仓库管理员吧

**Comment by Mrered** [comment]
> 我这几天项目有点忙，我加你为仓库管理员吧

感谢，我这两天在折腾 OpenWRT 设备，等我调试好了就把这几个 ruby 脚本写一下！

**Comment by ivaquero** [comment]
今天加班，晚上回去了弄哈

**Comment by Mrered** [comment]
看一下我发的 [pr](https://github.com/ivaquero/homebrew-chinese/pull/18) ，应该是没问题了。

**Comment by ivaquero** [comment]
Done
