### ISSUE TITLE
希望增加对 MessAuto 的支持

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#17]
[希望增加 macOS 上 Homebrew 包管理器安装方式的支持 · Issue #12 · LeeeSe/MessAuto (github.com)](https://github.com/LeeeSe/MessAuto/issues/12)

[LeeeSe/MessAuto: 自动提取Mac平台的短信验证码，2FHey的免费替代品；Automatic extraction of SMS verification code for Mac platform, free alternatives to 2FHey (github.com)](https://github.com/LeeeSe/MessAuto)

**Comment by ivaquero** [comment]
Messo 你切换分支再提交一次PR吧

**Comment by Mrered** [comment]
好嘞

**Comment by ivaquero** [comment]
合并了，今天碰巧休息
