### ISSUE TITLE
希望增加对 ddns-go 的支持

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#23]
[\[功能\]：希望增加对 macOS 上 Homebrew 包管理器安装方式的支持 · Issue #721 · jeessy2/ddns-go (github.com)](https://github.com/jeessy2/ddns-go/issues/721)

[jeessy2/ddns-go: 简单好用的DDNS。自动更新域名解析到公网IP(支持阿里云、腾讯云、Dnspod、Cloudflare、Callback、华为云、百度云、Porkbun、GoDaddy、Google Domain) (github.com)](https://github.com/jeessy2/ddns-go)

这是个formula，官方readme里有一段安装服务的介绍，我不会搞，呜呜呜😭

## 系统中使用

*   从 [Releases](https://github.com/jeessy2/ddns-go/releases) 下载并解压 ddns-go
*   双击运行, 如没有找到配置, 程序将自动打开 [http://127.0.0.1:9876](http://127.0.0.1:9876/)
*   \[可选\] 安装服务
    *   Mac/Linux: `sudo ./ddns-go -s install`
    *   Win(以管理员打开cmd): `.\ddns-go.exe -s install`
*   \[可选\] 服务卸载
    *   Mac/Linux: `sudo ./ddns-go -s uninstall`
    *   Win(以管理员打开cmd): `.\ddns-go.exe -s uninstall`
*   \[可选\] 支持安装或启动时带参数 `-l`监听地址 `-f`同步间隔时间(秒) `-cacheTimes`间隔N次与服务商比对 `-c`自定义配置文件路径 `-noweb`不启动web服务 `-skipVerify`跳过证书验证。如：`./ddns-go -s install -l :9877 -f 600 -c /Users/name/ddns-go.yaml`

> Note 通过合理的配置 `-f` 和 `-cacheTimes` 可以实现 IP 变化即时触发更新且不会被 DDNS 服务商限流, 例如 `-f 10 -cacheTimes 360` 效果为每 10 秒检查一次本地 IP 变化, 每小时去公网对比一下 IP 变化

**Comment by ivaquero** [comment]
这个我也不知道怎么用 formula 处理

**Comment by Mrered** [comment]
[ddns-go 5.3.1 (new formula) by WaterLemons2k · Pull Request #132725 · Homebrew/homebrew-core (github.com)](https://github.com/Homebrew/homebrew-core/pull/132725)有人在官方提交

**Comment by ivaquero** [comment]
挺好的，明天看看合并了没
