### ISSUE TITLE
我有空了给 Readme 加一下【简介】列

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#47]
如下

|                                         App 名                                          |                 简介                  |      Cask 名      |          类型           | 原创 |
| :-------------------------------------------------------------------------------------: | :-----------------------------------: | :---------------: | :---------------------: | :--: |
|                  [GridPlayer](https://github.com/vzhd1701/gridplayer)                   |      可同时播放多个视频的播放器       |    gridplayer     |       🆓开源软件        |  √   |
|                          [Pareto](https://paretosecurity.com/)                          |     检查 Mac 安全设置的菜单栏工具     |  pareto-security  |       🆓开源软件        |  √   |
|                       [PeaZip](https://github.com/peazip/PeaZip)                        |      文件压缩工具和 RAR 解压软件      |      peazip       |       🆓开源软件        |  √   |
|              [纤毫毕现](https://github.com/cormiertyshawn895/PixelPerfect)              | 在 Mac 上改善 iOS/iPadOS 应用的分辨率 |   pixel-perfect   |       🆓开源软件        |  √   |
|          [AList 官方桌面客户端](https://github.com/alist-org/desktop-release)           | 一站式让网盘、网络存储等变成本地硬盘  |   alist-desktop   | 💰开源软件（国人开发） |  √   |
| [Alist-Helper](https://github.com/Xmarmalade/alisthelper/blob/master/README_zh-Hans.md) |         第三方 AList 管理软件         |   alist-helper    | 🆓开源软件（国人开发）  |  √   |

……

**Comment by ivaquero** [comment]
简介会不会增加工作量？

**Comment by Mrered** [comment]
在发现咱们的仓库之后的第一时间，我就看到了软件列表，其中很多软件只看名字确实不知道是干啥的。

或者直接给软件名字加上官网超链接🔗？

**Comment by ivaquero** [comment]
我只是觉得超链接和链接，有点重复

**Comment by Mrered** [comment]
那就不加简介，直接给每个软件名字加上超链接

如下

|                                         App 名                                          |      Cask 名      |          类型           | 原创 |
| :-------------------------------------------------------------------------------------: | :---------------: | :---------------------: | :--: |
|                  [GridPlayer](https://github.com/vzhd1701/gridplayer)                   |   `gridplayer`    |       🆓开源软件        |  √   |
|                          [Pareto](https://paretosecurity.com/)                          | `pareto-security` |       🆓开源软件        |  √   |
|                       [PeaZip](https://github.com/peazip/PeaZip)                        |     `peazip`      |       🆓开源软件        |  √   |
|              [纤毫毕现](https://github.com/cormiertyshawn895/PixelPerfect)              |  `pixel-perfect`  |       🆓开源软件        |  √   |
|          [AList 官方桌面客户端](https://github.com/alist-org/desktop-release)           |  `alist-desktop`  | 💰开源软件（国人开发） |  √   |
| [Alist-Helper](https://github.com/Xmarmalade/alisthelper/blob/master/README_zh-Hans.md) |  `alist-helper`   | 🆓开源软件（国人开发）  |  √   |
……

**Comment by ivaquero** [comment]
好的，有劳了

**Comment by Mrered** [comment]
已完成所有 Cask 的超链接

- 🆓 可免费使用的软件
- 💰 须付费使用的软件
- 🆓💰 免费增值的软件

@ivaquero 需要排序

**Comment by ivaquero** [comment]
非常感谢！

**Comment by Mrered** [comment]
我只给我知道收费模式的软件加了 🆓 和 💰 的标志，麻烦你给其他的也加一下

**Comment by ivaquero** [comment]
Done
