### ISSUE TITLE
无法解决 zip 嵌套 dmg 的安装文件

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#81]
我发了一个 demo ，麻烦看一下怎么解决？

https://github.com/ivaquero/homebrew-chinese/blob/021471eaa408ca3c1f102d49ceb27cd83b47c344/Casks/tts-vue.rb#L18

**Comment by ivaquero** [comment]
试了一下，我解决不了

**Comment by Mrered** [comment]
只能寄希望于原作者了

**Comment by ivaquero** [comment]
你参考一下名为 openstudio 的脚本

**Comment by ivaquero** [comment]
<img width="877" alt="image" src="https://github.com/ivaquero/homebrew-chinese/assets/46377665/c43163e5-a156-4c72-a296-1fe6e2f34bdc">
这个软件，你在用么？里面明明不符合规范

**Comment by ivaquero** [comment]
> > 你参考一下名为 openstudio 的脚本
> 
> 
> 
> 你说的是这个吗？
> 
> 
> 
> https://github.com/ivaquero/homebrew-chinese/blob/0fe3e0f49cf8dd3eebf846365d7c15b1e4a4ff14/Casks/openstudio.rb#L16
> 
> 
> 
> 我感觉这是在指定可执行文件的位置？现在这个软件是 `.app` 文件塞到 `.dmg` 镜像里，再把 `.dmg` 压缩成 `.zip` 发布的。

我又看了一下，压缩两层确实有点反常

**Comment by ivaquero** [comment]
强！

**Comment by Mrered** [comment]
感谢 @Oscaner #91
