### ISSUE TITLE
无法获取到软件的下载链接

### ISSUE THREAD

**Issue by Mrered** [ivaquero/homebrew-chinese#83]
这是我写的 demo

https://github.com/ivaquero/homebrew-chinese/blob/1b09cab05aa2ac2e47563a800bfd1037aa998384/Casks/tinkertool.rb#L5

这个软件用的动态下载地址，我获取不到下载链接，求助。

**Comment by Mrered** [comment]
https://github.com/Homebrew/homebrew-cask/pull/9082

2015 年就出现了这个问题，工单关了。

**Comment by Mrered** [comment]
要不要把他们官网的 dmg 拉一份放到咱们仓库 release 里？

**Comment by ivaquero** [comment]
> Homebrew/homebrew-cask#9082

不大建议这么做
