### ISSUE TITLE
clash-verge-rev 的 sha256 不对

### ISSUE THREAD

**Issue by Oscaner** [ivaquero/homebrew-chinese#93]
<img width="650" alt="image" src="https://github.com/ivaquero/homebrew-chinese/assets/26829325/445c9038-d019-4f94-8867-c78b3f9e2c72">

```
Error: ivaquero/chinese/clash-verge-rev: SHA256 mismatch
Expected: eee067c90133eef7a05bc45228be3f4245be2417ae2b4b25d0e4965ad4838824
  Actual: 8c8175b10c1db2612d542ea0aee7bc6a12377817f6d0c1ecbfd2e64e18f02ad8
```

**Comment by Mrered** [comment]
https://github.com/ivaquero/homebrew-chinese/commit/32fd5e0b4be6a0265fe1c7e196980f077882017e
